### ISSUE TITLE
Battery drain question 

### ISSUE THREAD

**Issue by Big-Tree** [ohmae/orientation-faker#7]
Hi, the app has been very useful!  I'm wondering if there will be any additional drain on the battery?  How cpu/gpu intensive is it?

**Comment by ohmae** [comment]
This app has little effect on cpu and gpu. The process is just alive and does almost nothing. The mode to monitor the accelerometer will consume a little more power, and if  enabled the per-app settings, check the apps that are running once per second. However, all of them stop working when the screen goes off. Therefore, the effect on the battery is very small.
However, since  this app is always running in the foreground, the system may falsely detect it as a high power consumption app.
